[package]
name = "province_welder"
version = "0.1.0"
authors = ["ScottyThePilot <scotty.codes@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23"
util_macros = { git = "https://github.com/ScottyThePilot/util_macros" }
parse = { path = "../parse" }
rand = "0.8.3"
