[package]
name = "province_sniper"
version = "0.1.0"
authors = ["ScottyThePilot <scotty.codes@gmail.com>"]
edition = "2018"

[dependencies]
util_macros = { git = "https://github.com/ScottyThePilot/util_macros" }
parse = { path = "../parse" }
